#!/usr/bin/env python3
"""
vibe-20260815-2331 — Backend
Generated by MAHI Vibe Pipeline
"""

from flask import Flask, jsonify, request
from functools import wraps
import os

app = Flask(__name__)
app.config["SECRET_KEY"] = os.environ.get("SECRET_KEY", "dev-key-change-in-prod")


def require_auth(f):
    """Simple auth decorator (placeholder)."""
    @wraps(f)
    def decorated(*args, **kwargs):
        token = request.headers.get("Authorization")
        if not token:
            return jsonify({"error": "Missing auth token"}), 401
        return f(*args, **kwargs)
    return decorated


@app.route("/")
def index():
    return jsonify({"name": "vibe-20260815-2331", "status": "running"})


@app.route("/api/health")
def health():
    return jsonify({"status": "ok"})


@app.route("/api/data")
@require_auth
def get_data():
    return jsonify({"items": []})


if __name__ == "__main__":
    app.run(debug=True, port=5000)
